Implement changes for SAPP-2130
universityofadelaide/shepherd-drupal-scaffold pull request #108
Opened 2021-11-10 06:41 UTC by singularo

Knocked it up quickly, needs testing.

2021-11-10 07:51 UTC, behzad1q commented
it should be working but not 
![image](https://user-images.githubusercontent.com/13213064/141071935-65b92c2a-fffe-4ab1-a1bb-2f848dbbddb3.png)

2021-11-10 09:15 UTC, dpi requested changes
path structures need tweaking

2021-11-10 09:15 UTC, dpi commented on scaffold/required/monolog.services.yml
> +parameters:
This file should be moved to `scaffold/required/web/sites/default/monolog.services.yml`.

You can get inspiration from the docker files in `scafffold/optional/docker/`

2021-11-10 09:16 UTC, dpi commented
Should the remaining steps for how to activate monolog be added to Monolog? ie. composer.json, core.extension.yml entry, ...

2021-11-10 21:42 UTC, singularo commented
This seems to work, but having slept on it, I'm not sure we should be merging this, or even using monolog at all.

1. Monolog is cool and has lots of features, we're not using any of them, or planning to use any that i'm aware of.
2. We could integrate sending messages directly to splunk, but our experience doing things that way isn't good, so I don't think thats likely, especially given openshift will be logging to spunk already.
3. So then these scaffold changes add no new features?
4. Putting this in the scaffold makes a hard dependency in all projects that use it, and uninstalling monolog then breaks things:
```
$ drush cr
In DefinitionErrorExceptionPass.php line 54:
  You have requested a non-existent parameter "monolog.level.debug".
```
5. The settings.app.php could be used with a configmap to achieve the same result if individual sites require it.
6. monolog adds 10x the code for a bunch of features we're not using (and yes I know, not maintaining either).
144K	web/modules/contrib/monolog
724K	vendor/monolog/
88K	web/modules/contrib/log_stdout/

Unless we're logging to something other than stdout, why are we even switching?

2021-11-11 00:44 UTC, pingers commented
A couple of reasons I guess:
1. Monolog is the standard for php logging.
2. We can use a template for the log format - more parser friendly for splunk... one day.

2021-11-11 01:41 UTC, dpi commented
Ultimately it doesnt *need* to be in scaffold.

I think we just want to get off https://www.drupal.org/project/log_stdout onto something more standard.

2021-11-11 02:42 UTC, singularo commented
I'll leave it to @pingers to decide ;-P

2021-11-12 03:21 UTC, pingers commented
Need to check that we can still log to stdout + dblog. E.g. for multi-line log entries.

2021-11-12 05:00 UTC, singularo commented
With monolog enabled and configured as above, enabling dblog doesn't actually get any dblogs.
Changing the monolog.services.yml to have:
```
parameters:
  monolog.channel_handlers:
    default: ['drupal.dblog']
    php: ['drupal.db_log']
```

Does then log to dblog.

But, this requires changing the scaffold file in this commit, which would need to be overwritten with a configmap.

I feel that monolog is setup/configured at a lower level than works well in the OpenShift environment, so I'm going to suggest we not merge this, and in fact do move back to log_stdout for our use case, which is just simple stdout logging.

2021-11-23 00:17 UTC, singularo commented
Closing this

2021-11-23 00:17 UTC, closed without merging